"use client";

import { useState } from "react";
import Link from "next/link";
import { Icon } from "../../../components/icons";
import { MobileBottomNav, PageFrame, WorkspaceSidebar } from "../../../components/shell";
import { Avatar } from "../../../components/icons";
import { GreekDivider, IconButton, Tag } from "../../../components/ui";
import { MiniGraph, NetworkGraph } from "../../../components/visuals";

const entityFilters = ["All entities", "Authors", "Institutions", "Topics", "Papers"];

function AuthorInspector() {
  return <aside className="author-inspector paper-card"><div className="inspector-actions"><button type="button"><Icon name="chevronLeft" size={15} /></button><button type="button"><Icon name="chevronRight" size={15} /></button><IconButton label="Close inspector" name="close" size={17} /></div><div className="author-profile"><Avatar initials="YV" variant="violet" /><div><h2>Yasmin Vaswani <span className="verified">✦</span></h2><p><Icon name="building" size={15} /> Google Research</p><p><Icon name="pin" size={15} /> New York, USA</p></div></div><div className="research-areas"><strong>RESEARCH AREAS</strong><div><Tag>Natural Language Processing</Tag><Tag>Transformers</Tag><Tag>Attention Mechanisms</Tag><Tag>Deep Learning</Tag></div></div><div className="bibliometrics"><span><b>52</b><small>h-index</small></span><span><b>112</b><small>i10-index</small></span><span><b>16,842</b><small>Citations</small></span><span><b>47</b><small>Papers</small></span></div><section className="notable-papers"><div className="subheading"><strong>NOTABLE PAPERS</strong><a href="#all">View all <Icon name="arrow" size={14} /></a></div>{[["Attention Is All You Need", "Y. Vaswani, N. Shazeer, N. Parmar, ...", "NeurIPS, 2017", "18,520"], ["BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", "J. Devlin, M.-W. Chang, K. Lee, Y. Vaswani, ...", "NAACL, 2019", "24,768"], ["Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer", "C. Raffel, N. Shazeer, A. Roberts, Y. Vaswani, ...", "JMLR, 2020", "3,112"]].map(([title, authors, venue, citations], index) => <article key={title}><span>{index + 1}.</span><div><strong>{title}</strong><p>{authors}</p><a href="#paper">{venue}</a></div><b>{citations}<small>citations</small></b></article>)}</section><section className="collaboration"><strong>COLLABORATION SUMMARY</strong><div className="collaboration-stats"><span>Co-authors <b>128</b></span><span>Institutions <b>18</b></span><span>Countries <b>11</b></span><MiniGraph /></div><div className="collaborators"><strong>Top Collaborators</strong>{[["Noam Shazeer", "12"], ["Niki Parmar", "10"], ["Jakob Uszkoreit", "7"], ["Aidan N. Gomez", "6"], ["Llion Jones", "5"]].map(([name, count]) => <span key={name}>{name}<i style={{ "--collab": `${Number(count) / 12 * 100}%` } as React.CSSProperties} /><b>{count}</b></span>)}</div><a className="text-link" href="#network">View full collaboration network <Icon name="arrow" size={14} /></a></section><div className="external-sources"><Icon name="link" size={16} /><span><strong>OpenAlex / Semantic Scholar</strong><small>External metadata context</small></span></div></aside>;
}
export default function AuthorsPage() {
  const [entity, setEntity] = useState("All entities");
  return <PageFrame active="product" className="workspace-page authors-page" showBack backHref="/papers/attention-is-all-you-need"><div className="authors-layout"><WorkspaceSidebar selected="authors" section="explore" /><main className="authors-main"><section className="authors-title"><h1>Authors &amp; Research Graph</h1><GreekDivider /><p>Explore connections between authors, institutions, topics, and papers.</p></section><div className="graph-controls"><button type="button" className="select-button"><Icon name="graph" size={16} /> Graph view <Icon name="chevronDown" size={14} /></button><div className="entity-tabs">{entityFilters.map((item) => <button key={item} className={entity === item ? "is-active" : ""} type="button" onClick={() => setEntity(item)}><Icon name={item === "Authors" ? "authors" : item === "Institutions" ? "building" : item === "Topics" ? "tag" : item === "Papers" ? "file" : "globe"} size={15} />{item}</button>)}</div><button type="button" className="select-button"><Icon name="filter" size={15} /> Filters</button></div><div className="graph-canvas paper-card"><div className="graph-legend"><span><i className="legend-author" /> Author</span><span><i className="legend-institution" /> Institution</span><span><i className="legend-topic" /> Topic</span><span><i className="legend-paper" /> Paper</span><hr /><span><i className="legend-line solid" /> Co-authorship</span><span><i className="legend-line dashed" /> Related to</span></div><NetworkGraph /><div className="graph-zoom"><button type="button"><Icon name="plus" size={16} /></button><button type="button"><Icon name="minus" size={16} /></button><button type="button"><Icon name="fullscreen" size={16} /></button><button type="button"><Icon name="lock" size={16} /></button></div></div></main><AuthorInspector /></div><MobileBottomNav labels="explore" selected="explore" /></PageFrame>;
}
