"use client";

import { useState } from "react";
import { Icon } from "../../../components/icons";
import { MobileBottomNav, PageFrame, WorkspaceSidebar } from "../../../components/shell";
import { Avatar } from "../../../components/icons";
import { GreekDivider, IconButton, Tag } from "../../../components/ui";
import { MiniGraph, NetworkGraph } from "../../../components/visuals";
import { paperLinks } from "../../../components/data";

const entityFilters = ["All entities", "Authors", "Institutions", "Topics", "Papers"];

function AuthorInspector() {
  const notablePapers = [["Attention Is All You Need", "Y. Vaswani, N. Shazeer, N. Parmar, ...", "NeurIPS, 2017", paperLinks.abstract], ["BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", "J. Devlin, M.-W. Chang, K. Lee, Y. Vaswani, ...", "NAACL, 2019", "https://arxiv.org/abs/1810.04805"], ["Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer", "C. Raffel, N. Shazeer, A. Roberts, Y. Vaswani, ...", "JMLR, 2020", "https://arxiv.org/abs/1910.10683"]] as const;
  const collaborators = ["Noam Shazeer", "Niki Parmar", "Jakob Uszkoreit", "Aidan N. Gomez", "Llion Jones"];
  const [visible, setVisible] = useState(true);
  if (!visible) return <button type="button" className="button button-outline author-inspector-reopen" onClick={() => setVisible(true)}>Show author details <Icon name="arrow" size={14} /></button>;
  return <aside className="author-inspector paper-card"><div className="inspector-actions"><IconButton label="Close inspector" name="close" size={17} onClick={() => setVisible(false)} /></div><div className="author-profile"><Avatar initials="AV" variant="violet" /><div><h2>Ashish Vaswani</h2><p><Icon name="building" size={15} /> Author of the source paper</p><p><Icon name="pin" size={15} /> Metadata from the paper</p></div></div><div className="research-areas"><strong>RESEARCH AREAS</strong><div><Tag>Natural Language Processing</Tag><Tag>Transformers</Tag><Tag>Attention Mechanisms</Tag><Tag>Deep Learning</Tag></div></div><section className="notable-papers" id="notable-papers"><div className="subheading"><strong>NOTABLE PAPERS</strong><a href="#notable-papers">View all <Icon name="arrow" size={14} /></a></div>{notablePapers.map(([title, authors, venue, href], index) => <article key={title}><span>{index + 1}.</span><div><strong>{title}</strong><p>{authors}</p><a href={href} target="_blank" rel="noreferrer">{venue} <Icon name="external" size={11} /></a></div></article>)}</section><section className="collaboration" id="network"><strong>COLLABORATION SUMMARY</strong><div className="collaboration-stats"><span>Source paper <b>Authors</b></span><span>Research graph <b>Linked</b></span><MiniGraph /></div><div className="collaborators"><strong>Co-authors shown in this graph</strong>{collaborators.map((name) => <span key={name}>{name}<small>Source paper co-author</small></span>)}</div><a className="text-link" href="#network">View collaboration network <Icon name="arrow" size={14} /></a></section><div className="external-sources"><Icon name="link" size={16} /><span><strong>OpenAlex / Semantic Scholar</strong><small>External metadata context</small></span></div></aside>;
}
export default function AuthorsPage() {
  const [entity, setEntity] = useState("All entities");
  const [graphZoom, setGraphZoom] = useState(1);
  const [graphFullScreen, setGraphFullScreen] = useState(false);
  const [graphLocked, setGraphLocked] = useState(false);
  return <PageFrame active="product" className="workspace-page authors-page" showBack backHref="/papers/attention-is-all-you-need"><div className="authors-layout"><WorkspaceSidebar selected="authors" section="explore" /><main className="authors-main"><section className="authors-title"><h1>Authors &amp; Research Graph</h1><GreekDivider /><p>Explore connections between authors, institutions, topics, and papers.</p></section><div className="graph-controls" id="institutions"><button type="button" className="select-button" onClick={() => setGraphFullScreen((value) => !value)}><Icon name="graph" size={16} /> {graphFullScreen ? "Close graph" : "Graph view"} <Icon name="chevronDown" size={14} /></button><div className="entity-tabs" id="topics">{entityFilters.map((item) => <button key={item} className={entity === item ? "is-active" : ""} type="button" onClick={() => setEntity(item)}><Icon name={item === "Authors" ? "authors" : item === "Institutions" ? "building" : item === "Topics" ? "tag" : item === "Papers" ? "file" : "globe"} size={15} />{item}</button>)}</div><button type="button" className="select-button" onClick={() => { setEntity("All entities"); setGraphZoom(1); }}><Icon name="filter" size={15} /> Reset filters</button></div><div className={`graph-canvas paper-card ${graphFullScreen ? "is-fullscreen" : ""}`}><div className="graph-legend"><span><i className="legend-author" /> Author</span><span><i className="legend-institution" /> Institution</span><span><i className="legend-topic" /> Topic</span><span><i className="legend-paper" /> Paper</span><hr /><span><i className="legend-line solid" /> Co-authorship</span><span><i className="legend-line dashed" /> Related to</span></div><div className="graph-visual" style={{ transform: `scale(${graphZoom})` }}><NetworkGraph /></div><div className="graph-zoom"><button type="button" aria-label="Zoom in" onClick={() => setGraphZoom((value) => Math.min(1.3, value + .1))}><Icon name="plus" size={16} /></button><button type="button" aria-label="Zoom out" onClick={() => setGraphZoom((value) => Math.max(.8, value - .1))}><Icon name="minus" size={16} /></button><button type="button" aria-label={graphFullScreen ? "Exit full screen" : "Fit graph"} onClick={() => { setGraphZoom(1); setGraphFullScreen((value) => !value); }}><Icon name="fullscreen" size={16} /></button><button type="button" aria-label={graphLocked ? "Unlock graph" : "Lock graph"} aria-pressed={graphLocked} onClick={() => setGraphLocked((value) => !value)}><Icon name="lock" size={16} /></button></div></div></main><AuthorInspector /></div><MobileBottomNav labels="explore" selected="explore" /></PageFrame>;
}
