"use client";

import { useState } from "react";
import { Icon } from "../../../components/icons";
import { MobileBottomNav, MobilePaperContext, PageFrame, WorkspaceSidebar } from "../../../components/shell";
import { methodCards } from "../../../components/data";
import { IconButton, Tag } from "../../../components/ui";

const anatomy = [
  ["WHY", "Research Question", "Can attention mechanisms replace recurrence and convolutions for sequence translation?", "target"],
  ["HOW", "Approach & Design", "Propose a Transformer model based solely on attention mechanisms; compare to state-of-the-art.", "methods"],
  ["WHAT THEY FOUND", "Results", "Transformer achieves state-of-the-art on machine translation tasks with greater efficiency.", "chart"],
  ["SO WHAT", "Implications", "Attention-only models are a general-purpose architecture for sequence modeling.", "balance"],
] as const;

const lensRows = [["Internal Validity", "Low risk", "violet"], ["External Validity", "Medium risk", "gold"], ["Measurement", "Low risk", "violet"], ["Bias", "Medium risk", "gold"], ["Reproducibility", "Low risk", "violet"]] as const;

function MethodLens() {
  const [open, setOpen] = useState<string | null>(null);
  return <aside className="method-lens paper-card"><div className="lens-heading"><Icon name="building" size={22} /><div><h2>Method Lens</h2><p>At-a-glance assessment of rigor and trustworthiness.</p></div></div><section className="lens-section lens-strengths"><h3><span><Icon name="check" size={16} /></span> Strengths</h3><ul><li>Clear research question and motivation.</li><li>Strong empirical results on standard benchmarks.</li><li>Transparent architecture and training details.</li><li>Ablation studies support design choices.</li></ul></section><section className="lens-section lens-caveats"><h3><span><Icon name="warning" size={16} /></span> Caveats</h3><ul><li>Benchmarks may not capture real-world deployment.</li><li>Limited analysis on robustness and fairness.</li><li>Compute-intensive; reproducibility may be a barrier.</li></ul></section><section className="lens-section lens-not-prove"><h3><span><Icon name="close" size={16} /></span> What this paper does NOT prove</h3><ul><li>It does not prove attention is always superior—only in tested settings.</li><li>It does not prove causal claims about underlying linguistic structure.</li></ul></section><div className="lens-accordion">{lensRows.map(([label, risk, tone]) => <button key={label} type="button" onClick={() => setOpen(open === label ? null : label)}><span><Icon name={label === "Measurement" ? "target" : label === "Bias" ? "users" : label === "Reproducibility" ? "refresh" : "building"} size={16} />{label}</span><em className={`risk-${tone}`}>{risk}</em><Icon name={open === label ? "chevronDown" : "chevronRight"} size={15} />{open === label ? <small>Reasoned from the paper&apos;s data, design, and reported evaluation context.</small> : null}</button>)}</div><a className="text-link" href="#framework">About our evaluation framework <Icon name="arrow" size={14} /></a></aside>;
}
export default function MethodsPage() {
  return <PageFrame active="product" className="workspace-page methods-page"><div className="methods-layout"><WorkspaceSidebar selected="methods" /><main className="methods-main"><MobilePaperContext label="Methods" /><div className="methods-heading"><div><h1>Methods &amp; Limitations</h1><p>A structured breakdown of how the study was done—and what it can (and can&apos;t) tell us.</p></div><button type="button" className="button button-outline"><Icon name="download" size={16} /> Export summary</button></div><div className="methods-content"><section className="methods-analysis"><h2>Visual anatomy of the paper</h2><div className="anatomy-flow">{anatomy.map(([label, title, text, icon], index) => <article key={label} className="anatomy-step"><div className="anatomy-icon"><Icon name={icon as never} size={22} /></div><strong>{label}</strong><div><h3>{title}</h3><p>{text}</p></div>{index < anatomy.length - 1 ? <span className="anatomy-arrow"><Icon name="chevronDown" size={17} /></span> : null}</article>)}</div></section><section className="methods-grid-section"><h2>How the study was conducted</h2><div className="methods-card-grid">{methodCards.map(([title, text, icon]) => <article className="method-card paper-card" key={title}><h3><Icon name={icon as never} size={20} />{title}</h3><p>{text}</p><a href={`#${title.toLowerCase().replaceAll(" ", "-")}`}>View details <Icon name="arrow" size={14} /></a></article>)}</div><article className="limitations-card paper-card"><h3><Icon name="warning" size={20} /> Limitations <small>(as stated by authors)</small></h3><ul><li>Performance on very long sequences remains challenging.</li><li>Results shown for machine translation; generalization to other tasks needs study.</li><li>Model size and compute requirements can be substantial.</li></ul><a href="#limitations">View full limitations section <Icon name="arrow" size={14} /></a></article></section></div></main><MethodLens /></div><MobileBottomNav selected="more" /></PageFrame>;
}
